/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pokeball.gltf 
Author: JMGameDev (https://sketchfab.com/JMGameDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-basic-pokeball-9b29539199c14ddea4de7776c4d758df
Title: Pokemon Basic Pokeball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pokeball.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PokeBall__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={0.04} />
    </group>
  )
}

useGLTF.preload('/pokeball.gltf')
